name = "cold-meadow-05ba"
main = "scripts/routes.js"

account_id = "428f2588ad08b3ef1e44b4a80ca23263"
workers_dev = true
compatibility_date = "2024-08-05"

[env.dev]
zone_id = "ccd41d45cccf9e6c100b10a55013b29d"
route = "dex-v3-api-aws.lootex.dev/*"